Upload version 0.3

diff --git a/nvidia-headless-utils/src/bin/Xorg-nvidia-headless b/nvidia-headless-utils/src/bin/Xorg-nvidia-headless
--- a/nvidia-headless-utils/src/bin/Xorg-nvidia-headless
+++ b/nvidia-headless-utils/src/bin/Xorg-nvidia-headless
@@ -1,3 +1,17 @@
 #!/bin/sh
-. %%PREFIX%%/etc/nvidia-headless.conf
-exec %%PREFIX%%/bin/Xorg -sharevts -novtswitch -noreset -config xorg-nvidia-headless.conf "$NVDISPLAY" "$@"
+conf=%%PREFIX%%/etc/nvidia-headless.conf
+. %%PREFIX%%/libexec/nvidia-headless-utils/readconf
+if [ -z "$NVDISPLAY" ]; then printf %s\\n "NVDISPLAY required in environment or in $conf" >&2 ; exit 1; fi
+xconfig=%%LOCALBASE%%/etc/X11/xorg-nvidia-headless.conf
+xconfarg=xorg-nvidia-headless.conf
+if [ ! -e "$xconfig" ]; then
+if [ "$(id -u)" != 0 ]; then
+printf %s\\n "nvidia-headless must be configured by superuser" >&2
+exit 1
+fi
+xconfig=/var/cache/nvidia-headless/xorg.conf
+mkdir -p /var/cache/nvidia-headless
+xconfarg="$xconfig"
+%%PREFIX%%/bin/nvidia-headless-xconfig -o "$xconfig"
+fi
+exec %%LOCALBASE%%/bin/Xorg -sharevts -novtswitch -noreset -config "$xconfarg" "$NVDISPLAY" "$@"
